// client/src/components/ResponseTable.vue
<script setup lang="ts">
import { ref, computed } from 'vue';
import axios from 'axios';
import { API_BASE_URL } from '../config';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { Search, Download, Trash2 } from 'lucide-vue-next';

const props = defineProps<{
  initialResponses: any[];
  questions: any[];
  surveyTitle: { tr: string, en: string };
}>();

const responses = ref(props.initialResponses);
const searchTerm = ref('');
const deleting = ref<string | null>(null);
const selectedResponse = ref<any>(null);

const filteredResponses = computed(() => {
  if (!searchTerm.value) return responses.value;
  const term = searchTerm.value.toLowerCase();
  return responses.value.filter(r => {
    let c: any = {};
    try { c = JSON.parse(r.customerInfo); } catch { }
    return (c.fullName || '').toLowerCase().includes(term) ||
           (c.companyName || '').toLowerCase().includes(term) ||
           (c.email || '').toLowerCase().includes(term);
  });
});

const handleDelete = async (id: string) => {
  if (!confirm('Bu yanıtı silmek istediğinize emin misiniz?')) return;
  deleting.value = id;
  try {
    await axios.delete(`${API_BASE_URL}/api/survey/response/${id}`);
    responses.value = responses.value.filter(r => r.id !== id);
  } catch (err) {
    alert('Silme hatası');
  } finally {
    deleting.value = null;
  }
};

const preparePDF = async () => {
  const doc = new jsPDF();
  try {
    const fontRes = await fetch('/fonts/Roboto-Regular.ttf');
    if (!fontRes.ok) throw new Error('Font not found');
    const fontBlob = await fontRes.blob();
    const fontData = await new Promise<string>((resolve) => {
      const reader = new FileReader();
      reader.onloadend = () => resolve(reader.result as string);
      reader.readAsDataURL(fontBlob);
    });
    const fontBase64 = fontData.split(',')[1] || '';
    doc.addFileToVFS('Roboto-Regular.ttf', fontBase64);
    doc.addFont('Roboto-Regular.ttf', 'Roboto', 'normal');
    doc.setFont('Roboto');
  } catch (err) {
    console.warn('Turkish font loading failed, using default font', err);
  }
  return doc;
};

const handleExportPDF = async () => {
  const doc = await preparePDF();
  const hasRoboto = !!doc.getFontList().Roboto;
  
  // Set font to ensure text() and table use it
  if (hasRoboto) {
    try { doc.setFont('Roboto'); } catch {}
  }
  
  doc.setFontSize(16);
  doc.text(props.surveyTitle.tr || 'Anket Yanitlari', 14, 20);
  if (props.initialResponses[0]?.survey?.revision) {
    doc.setFontSize(10);
    doc.text(`Rev: ${props.initialResponses[0].survey.revision}`, doc.internal.pageSize.width - 30, 20);
  }
  
  const head = [['Müşteri', ...props.questions.map((_, i) => `S${i + 1}`), 'Tarih']];
  const body = filteredResponses.value.map(r => {
    let c: any = {};
    try { c = JSON.parse(r.customerInfo); } catch { }
    const ansList = props.questions.map(q => {
      const a = (r.answers || []).find((ans: any) => ans.questionId === q.id);
      return a ? String(a.value) : '-';
    });
    return [c.fullName || '-', ...ansList, new Date(r.createdAt).toLocaleDateString()];
  });

  autoTable(doc, { 
    head, 
    body, 
    startY: 30,
    styles: { 
      font: hasRoboto ? 'Roboto' : 'helvetica',
      fontSize: 8 // Smaller font for bulk table to fit more columns
    },
    margin: { horizontal: 10 },
    didDrawPage: (data) => {
      // Add page number
      doc.setFontSize(8);
      doc.text(`Sayfa ${data.pageNumber}`, doc.internal.pageSize.width - 25, doc.internal.pageSize.height - 10);
    }
  });
  doc.save('anket-yanitlari.pdf');
};

const handleExportDetailPDF = async (response: any) => {
  const doc = await preparePDF();
  try { doc.setFont('Roboto'); } catch {}

  let c: any = {};
  try { c = JSON.parse(response.customerInfo); } catch { }

  doc.setFontSize(18);
  doc.text(props.surveyTitle.tr, 14, 20);
  if (response.survey?.revision) {
    doc.setFontSize(10);
    doc.text(`Rev: ${response.survey.revision}`, doc.internal.pageSize.width - 30, 20);
  }
  
  doc.setFontSize(12);
  doc.text('Müşteri Bilgileri:', 14, 35);
  doc.text(`İsim: ${c.fullName || '-'}`, 14, 45);
  doc.text(`Şirket: ${c.companyName || '-'}`, 14, 52);
  doc.text(`E-posta: ${c.email || '-'}`, 14, 59);
  doc.text(`Telefon: ${c.phone || '-'}`, 14, 66);
  doc.text(`Dil: ${response.language.toUpperCase()}`, 14, 73);
  doc.text(`Tarih: ${new Date(response.createdAt).toLocaleString()}`, 14, 80);

  const head = [['Soru', 'Cevap']];
  const body = props.questions.map((q, i) => {
    const a = response.answers.find((ans: any) => ans.questionId === q.id);
    const qText = response.language === 'en' ? q.textEN : q.textTR;
    return [`${i + 1}. ${qText}`, a ? a.value : '-'];
  });

  autoTable(doc, { 
    head, 
    body, 
    startY: 90,
    styles: { 
      font: doc.getFontList().Roboto ? 'Roboto' : 'helvetica',
      overflow: 'linebreak', 
      cellWidth: 'wrap' 
    },
    columnStyles: { 0: { cellWidth: 100 }, 1: { cellWidth: 'auto' } }
  });

  doc.save(`yanit-${c.fullName || 'detay'}.pdf`);
};

const openDetails = (response: any) => {
  selectedResponse.value = response;
};
</script>

<template>
  <div class="response-table-area">
    <div class="table-actions">
      <div class="search-box">
        <Search class="search-icon" />
        <input v-model="searchTerm" placeholder="Müşteri, şirket veya e-posta ara..." />
      </div>
      <button @click="handleExportPDF" class="export-btn">
        <Download class="icon" /> Tabloyu İndir (PDF)
      </button>
    </div>

    <div class="table-container">
      <table>
        <thead>
          <tr>
            <th>Müşteri / Şirket</th>
            <th>Dil</th>
            <th>Tarih</th>
            <th class="actions-th">İşlemler</th>
          </tr>
        </thead>
        <tbody>
          <tr v-for="r in filteredResponses" :key="r.id" @click="openDetails(r)">
            <td>
              <div class="customer-info" v-if="(() => { try { return JSON.parse(r.customerInfo); } catch { return {}; } })() as any">
                <span class="name">{{ (JSON.parse(r.customerInfo) as any).fullName }}</span>
                <span class="company">{{ (JSON.parse(r.customerInfo) as any).companyName }}</span>
              </div>
            </td>
            <td>
              <span :class="['lang-tag', r.language]">{{ r.language.toUpperCase() }}</span>
            </td>
            <td>{{ new Date(r.createdAt).toLocaleDateString() }}</td>
            <td class="actions-td">
              <button @click.stop="handleDelete(r.id)" :disabled="deleting === r.id" class="delete-btn">
                <Trash2 class="icon" />
              </button>
            </td>
          </tr>
          <tr v-if="filteredResponses.length === 0">
            <td colspan="4" class="empty-msg">Yanıt bulunamadı.</td>
          </tr>
        </tbody>
      </table>
    </div>

    <!-- Details Modal -->
    <div v-if="selectedResponse" class="modal-overlay" @click="selectedResponse = null">
      <div class="modal" @click.stop>
        <header>
          <h2>Yanıt Detayı</h2>
          <div class="modal-header-actions">
            <button @click="handleExportDetailPDF(selectedResponse)" class="detail-export-btn">
              <Download class="icon" /> PDF İndir
            </button>
            <button @click="selectedResponse = null" class="close-btn">&times;</button>
          </div>
        </header>
        <div class="modal-body">
          <div class="info-section">
            <h4>Müşteri Bilgileri</h4>
            <div class="info-grid" v-if="JSON.parse(selectedResponse.customerInfo) as any">
              <p><strong>İsim:</strong> {{ (JSON.parse(selectedResponse.customerInfo) as any).fullName }}</p>
              <p><strong>Şirket:</strong> {{ (JSON.parse(selectedResponse.customerInfo) as any).companyName }}</p>
              <p><strong>E-posta:</strong> {{ (JSON.parse(selectedResponse.customerInfo) as any).email }}</p>
              <p><strong>Telefon:</strong> {{ (JSON.parse(selectedResponse.customerInfo) as any).phone }}</p>
            </div>
          </div>
          <div class="answers-section">
            <h4>Soru ve Yanıtlar</h4>
            <div v-for="(q, i) in props.questions" :key="q.id" class="answer-item">
              <p class="q-text">{{ i + 1 }}. {{ selectedResponse.language === 'en' ? q.textEN : q.textTR }}</p>
              <p class="a-text">{{ selectedResponse.answers.find((a: any) => a.questionId === q.id)?.value || '-' }}</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<style scoped>
.table-actions {
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-bottom: 1.5rem;
  gap: 1rem;
}

.search-box {
  position: relative;
  flex: 1;
  max-width: 400px;
}

.search-icon {
  position: absolute;
  left: 1rem;
  top: 50%;
  transform: translateY(-50%);
  color: #94a3b8;
  width: 1.1rem;
}

.search-box input {
  width: 100%;
  padding: 0.75rem 1rem 0.75rem 2.75rem;
  border-radius: 0.75rem;
  border: 1px solid #e2e8f0;
}

.export-btn {
  display: flex;
  align-items: center;
  gap: 0.5rem;
  padding: 0.75rem 1.25rem;
  background: white;
  border: 1px solid #e2e8f0;
  border-radius: 0.75rem;
  font-weight: 600;
  cursor: pointer;
}

.table-container {
  background: white;
  border-radius: 1rem;
  border: 1px solid #e2e8f0;
  overflow: hidden;
}

table {
  width: 100%;
  border-collapse: collapse;
}

th {
  background: #f8fafc;
  padding: 1rem;
  text-align: left;
  font-weight: 600;
  color: #64748b;
  border-bottom: 1px solid #e2e8f0;
}

td {
  padding: 1rem;
  border-bottom: 1px solid #f1f5f9;
}

tr:hover {
  background: #f8fafc;
  cursor: pointer;
}

.customer-info .name {
  display: block;
  font-weight: 700;
  color: #1e293b;
}

.customer-info .company {
  font-size: 0.85rem;
  color: #64748b;
}

.lang-tag {
  padding: 0.25rem 0.5rem;
  border-radius: 0.4rem;
  font-size: 0.75rem;
  font-weight: 700;
}

.lang-tag.tr { background: #fee2e2; color: #991b1b; }
.lang-tag.en { background: #dbeafe; color: #1e40af; }

.actions-td, .actions-th {
  text-align: right;
}

.delete-btn {
  color: #ef4444;
  background: transparent;
  border: none;
  cursor: pointer;
  padding: 0.5rem;
}

.empty-msg {
  text-align: center;
  padding: 3rem;
  color: #64748b;
}

/* Modal */
.modal-overlay {
  position: fixed;
  top: 0; left: 0; right: 0; bottom: 0;
  background: rgba(0,0,0,0.5);
  display: flex;
  align-items: center; justify-content: center;
  z-index: 1000;
  padding: 1rem;
}

.modal {
  background: white;
  padding: 2rem;
  border-radius: 1.5rem;
  width: 100%;
  max-width: 800px;
  max-height: 90vh;
  overflow-y: auto;
}

.modal header {
  display: flex;
  justify-content: space-between;
  margin-bottom: 2rem;
}

.close-btn {
  background: none; border: none; font-size: 1.5rem; cursor: pointer;
  display: flex; align-items: center; justify-content: center;
  width: 2rem; height: 2rem;
}

.modal-header-actions {
  display: flex;
  align-items: center;
  gap: 1rem;
}

.detail-export-btn {
  display: flex;
  align-items: center;
  gap: 0.5rem;
  padding: 0.5rem 1rem;
  background: #6366f1;
  color: white;
  border: none;
  border-radius: 0.5rem;
  font-weight: 600;
  cursor: pointer;
  font-size: 0.9rem;
}

.info-section, .answers-section {
  margin-bottom: 2rem;
}

h4 {
  color: #6366f1;
  margin-bottom: 1rem;
  border-bottom: 1px solid #f1f5f9;
  padding-bottom: 0.5rem;
}

.info-grid {
  display: grid;
  grid-template-columns: 1fr 1fr;
  gap: 1rem;
}

.answer-item {
  margin-bottom: 1rem;
  padding-bottom: 1rem;
  border-bottom: 1px solid #f1f5f9;
}

.q-text { font-weight: 600; margin-bottom: 0.25rem; }
.a-text { color: #475569; }

.icon { width: 1.1rem; height: 1.1rem; }
</style>

// legacy/components/ResponseTable.tsx
'use client';

import { useState } from 'react';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

interface Props {
    initialResponses: any[];
    questions: any[];
    surveyTitle: { tr: string, en: string };
}

export default function ResponseTable({ initialResponses, questions, surveyTitle }: Props) {
    const [responses, setResponses] = useState(initialResponses);
    const [deleting, setDeleting] = useState<string | null>(null);

    const handleDelete = async (id: string) => {
        if (!confirm('Delete this response?')) return;

        setDeleting(id);
        try {
            const res = await fetch(`/api/survey/response/${id}`, { method: 'DELETE' });
            if (!res.ok) throw new Error('Failed');
            setResponses(responses.filter(r => r.id !== id));
        } catch (e) {
            alert('Error deleting response');
        } finally {
            setDeleting(null);
        }
    };

    const handleExportPDF = async () => {
        const doc = new jsPDF();

        // Add font
        const fontResponse = await fetch('/fonts/Amiri-Regular.ttf');
        const fontBlob = await fontResponse.blob();
        const reader = new FileReader();
        reader.readAsDataURL(fontBlob);

        reader.onloadend = () => {
            const base64data = reader.result as string;
            // Remove "data:font/ttf;base64," prefix
            const fontBase64 = base64data.split(',')[1];

            doc.addFileToVFS('Amiri-Regular.ttf', fontBase64);
            doc.addFont('Amiri-Regular.ttf', 'Amiri', 'normal');
            doc.setFont('Amiri');

            doc.setFontSize(16);
            doc.text(surveyTitle.tr, 14, 20);
            doc.setFontSize(10);
            doc.text(`Toplam Cevap: ${responses.length}`, 14, 28);

            const head = [
                ['Müşteri', ...questions.map((q, i) => `S${i + 1}`), 'Tarih']
            ];

            const body = responses.map(r => {
                let c = {};
                try { c = JSON.parse(r.customerInfo); } catch { }
                // @ts-ignore
                const customerStr = `${c.fullName || ''}\n${c.companyName || ''}`;

                const answers = questions.map(q => {
                    const a = r.answers.find((ans: any) => ans.questionId === q.id);
                    let val = a ? a.value : '-';
                    if (val === 'Yes') val = 'Evet';
                    if (val === 'No') val = 'Hayır';
                    return val;
                });

                return [customerStr, ...answers, new Date(r.createdAt).toLocaleDateString('tr-TR')];
            });

            autoTable(doc, {
                head: head,
                body: body,
                startY: 35,
                styles: { fontSize: 8, font: 'Amiri' },
                headStyles: { fillColor: [66, 66, 66] }
            });

            doc.save('anket-cevaplari.pdf');
        };
    };

    const handleSingleExport = async (response: any) => {
        const doc = new jsPDF();

        // Add font
        const fontResponse = await fetch('/fonts/Amiri-Regular.ttf');
        const fontBlob = await fontResponse.blob();
        const reader = new FileReader();
        reader.readAsDataURL(fontBlob);

        reader.onloadend = () => {
            const base64data = reader.result as string;
            const fontBase64 = base64data.split(',')[1];

            doc.addFileToVFS('Amiri-Regular.ttf', fontBase64);
            doc.addFont('Amiri-Regular.ttf', 'Amiri', 'normal');
            doc.setFont('Amiri');

            let customer: any = {};
            try {
                customer = JSON.parse(response.customerInfo);
            } catch { }

            const isEn = response.language === 'en';

            // Header
            doc.setFontSize(22);
            doc.setTextColor(40, 40, 40);
            doc.text(isEn ? 'Survey Response Document' : 'Anket Cevap Dökümanı', 105, 20, { align: 'center' });

            doc.setFontSize(12);
            doc.setTextColor(100, 100, 100);
            doc.text(isEn ? surveyTitle.en : surveyTitle.tr, 105, 28, { align: 'center' });

            doc.line(20, 35, 190, 35);

            // Details Info Box
            doc.setFillColor(245, 245, 245);
            doc.rect(20, 40, 170, 35, 'F');

            doc.setFontSize(10);
            doc.setTextColor(60, 60, 60);
            const dateStr = new Date(response.createdAt).toLocaleString(isEn ? 'en-US' : 'tr-TR');
            doc.text(`${isEn ? 'Date' : 'Tarih'}: ${dateStr}`, 25, 48);
            doc.text(`ID: ${response.id}`, 190, 48, { align: 'right' });

            doc.setFontSize(12);
            doc.setTextColor(0, 0, 0);
            doc.text(`${customer.fullName || '-'}`, 25, 58);
            doc.setFontSize(10);
            doc.setTextColor(80, 80, 80);
            doc.text(`${customer.companyName || '-'}`, 25, 64);
            doc.text(`${customer.email || '-'}  |  ${customer.phone || '-'}`, 25, 70);

            const locStr = `${customer.country || ''} - ${customer.address || ''}`;
            if (locStr.trim() !== '-') doc.text(locStr, 25, 76);

            // Q & A Section
            let yPos = 96;
            doc.setFontSize(14);
            doc.setTextColor(0, 0, 0);
            doc.text(isEn ? 'Responses' : 'Cevaplar', 20, 85);

            questions.forEach((q, i) => {
                if (yPos > 270) {
                    doc.addPage();
                    yPos = 20;
                }

                const answer = response.answers.find((a: any) => a.questionId === q.id);
                let val = answer?.value || (isEn ? 'No Answer' : 'Cevap Yok');

                if (val === 'Yes') val = isEn ? 'Yes' : 'Evet';
                if (val === 'No') val = isEn ? 'No' : 'Hayır';

                // Question Box
                doc.setFillColor(240, 248, 255);
                doc.rect(20, yPos, 170, 8, 'F');
                doc.setFontSize(10);
                // doc.setFont('helvetica', 'bold');
                doc.setTextColor(40, 40, 40);
                const qTitle = `Q${i + 1}: ${isEn ? q.textEN : q.textTR}`;
                doc.text(qTitle, 22, yPos + 6);

                yPos += 14;

                // Answer
                // doc.setFont('helvetica', 'normal');
                doc.setFontSize(11);
                doc.setTextColor(0, 0, 0);

                // Handle long text wrapping
                const answerLines = doc.splitTextToSize(val, 160);
                doc.text(answerLines, 25, yPos);

                yPos += (answerLines.length * 6) + 6;
            });

            // Footer
            const pageCount = doc.getNumberOfPages();
            for (let i = 1; i <= pageCount; i++) {
                doc.setPage(i);
                doc.setFontSize(8);
                doc.setTextColor(150, 150, 150);
                if (isEn) {
                    doc.text(`Page ${i} / ${pageCount}`, 190, 287, { align: 'right' });
                    doc.text(`Generated: ${new Date().toLocaleDateString('en-US')}`, 20, 287);
                } else {
                    doc.text(`Sayfa ${i} / ${pageCount}`, 190, 287, { align: 'right' });
                    doc.text(`Oluşturulma: ${new Date().toLocaleDateString('tr-TR')}`, 20, 287);
                }
            }

            doc.save(`Cevap_${customer.fullName?.replace(/\s+/g, '_') || 'Bilinmeyen'}_${new Date().toISOString().split('T')[0]}.pdf`);
        };
    };

    const [selectedResponse, setSelectedResponse] = useState<any>(null);
    const [searchTerm, setSearchTerm] = useState('');

    const filteredResponses = responses.filter(r => {
        if (!searchTerm) return true;
        const term = searchTerm.toLowerCase();
        let c: any = {};
        try { c = JSON.parse(r.customerInfo); } catch { }

        const name = (c.fullName || '').toLowerCase();
        const company = (c.companyName || '').toLowerCase();
        const email = (c.email || '').toLowerCase();

        return name.includes(term) || company.includes(term) || email.includes(term);
    });

    return (
        <div>
            {/* Modal for Details */}
            {selectedResponse && (
                <div style={{
                    position: 'fixed',
                    top: 0,
                    left: 0,
                    right: 0,
                    bottom: 0,
                    backgroundColor: 'rgba(0,0,0,0.5)',
                    display: 'flex',
                    justifyContent: 'center',
                    alignItems: 'center',
                    zIndex: 1000
                }} onClick={() => setSelectedResponse(null)}>
                    <div style={{
                        backgroundColor: 'var(--surface)',
                        padding: '30px',
                        borderRadius: 'var(--radius-lg)',
                        width: '90%',
                        maxWidth: '800px',
                        maxHeight: '90vh',
                        overflowY: 'auto',
                        boxShadow: 'var(--shadow-xl)',
                        position: 'relative'
                    }} onClick={e => e.stopPropagation()}>
                        <button
                            onClick={() => setSelectedResponse(null)}
                            style={{
                                position: 'absolute',
                                top: '20px',
                                right: '20px',
                                background: 'none',
                                border: 'none',
                                fontSize: '1.5rem',
                                cursor: 'pointer',
                                color: 'var(--text-muted)'
                            }}
                        >
                            &times;
                        </button>

                        <h2 style={{ fontSize: '1.5rem', marginBottom: '20px', paddingBottom: '10px', borderBottom: '1px solid var(--border)' }}>
                            {selectedResponse.language === 'en' ? 'Response Details' : 'Cevap Detayları'}
                        </h2>

                        <div style={{ display: 'grid', gap: '24px' }}>
                            {/* Customer Info */}
                            <div style={{ backgroundColor: 'var(--background)', padding: '20px', borderRadius: 'var(--radius)' }}>
                                <h3 style={{ fontSize: '1.1rem', marginBottom: '12px', color: 'var(--primary)' }}>
                                    {selectedResponse.language === 'en' ? 'Customer Information' : 'Müşteri Bilgileri'}
                                </h3>
                                <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '16px' }}>
                                    {(() => {
                                        try {
                                            const c = JSON.parse(selectedResponse.customerInfo);
                                            return (
                                                <>
                                                    <div><strong>{selectedResponse.language === 'en' ? 'Name' : 'İsim'}:</strong> {c.fullName}</div>
                                                    <div><strong>{selectedResponse.language === 'en' ? 'Company' : 'Şirket'}:</strong> {c.companyName}</div>
                                                    <div><strong>Email:</strong> {c.email}</div>
                                                    <div><strong>{selectedResponse.language === 'en' ? 'Phone' : 'Telefon'}:</strong> {c.phone}</div>
                                                    <div><strong>{selectedResponse.language === 'en' ? 'Country' : 'Ülke'}:</strong> {c.country || '-'}</div>
                                                    <div><strong>{selectedResponse.language === 'en' ? 'Address' : 'Adres'}:</strong> {c.address || '-'}</div>
                                                </>
                                            );
                                        } catch { return <div>Error parsing info</div> }
                                    })()}
                                </div>
                            </div>

                            {/* Answers */}
                            <div>
                                <h3 style={{ fontSize: '1.1rem', marginBottom: '16px', color: 'var(--primary)' }}>
                                    {selectedResponse.language === 'en' ? 'Answers' : 'Cevaplar'}
                                </h3>
                                <div style={{ display: 'grid', gap: '16px' }}>
                                    {questions.map((q, i) => {
                                        const ans = selectedResponse.answers.find((a: any) => a.questionId === q.id);
                                        let val = ans?.value || '-';
                                        if (val === 'Yes') val = selectedResponse.language === 'en' ? 'Yes' : 'Evet';
                                        if (val === 'No') val = selectedResponse.language === 'en' ? 'No' : 'Hayır';

                                        return (
                                            <div key={q.id} style={{ borderBottom: '1px solid var(--border)', paddingBottom: '12px' }}>
                                                <div style={{ fontWeight: 600, marginBottom: '4px' }}>
                                                    {i + 1}. {selectedResponse.language === 'en' ? q.textEN : q.textTR}
                                                </div>
                                                <div style={{ color: 'var(--foreground)' }}>{val}</div>
                                            </div>
                                        );
                                    })}
                                </div>
                            </div>
                        </div>

                        <div style={{ marginTop: '30px', display: 'flex', justifyContent: 'flex-end' }}>
                            <button
                                onClick={() => handleSingleExport(selectedResponse)}
                                style={{
                                    backgroundColor: 'var(--primary)',
                                    color: 'white',
                                    padding: '10px 24px',
                                    borderRadius: 'var(--radius)',
                                    border: 'none',
                                    cursor: 'pointer',
                                    fontWeight: 600
                                }}
                            >
                                {selectedResponse.language === 'en' ? 'Download PDF' : 'PDF İndir'}
                            </button>
                        </div>
                    </div>
                </div>
            )}

            <div style={{ marginBottom: '20px', display: 'flex', alignItems: 'center', gap: '20px' }}>
                <div style={{ flex: 1 }}>
                    <input
                        type="text"
                        placeholder="Ara: İsim, Şirket veya E-posta..."
                        value={searchTerm}
                        onChange={e => setSearchTerm(e.target.value)}
                        style={{
                            width: '100%',
                            maxWidth: '400px',
                            padding: '12px 16px',
                            borderRadius: 'var(--radius)',
                            border: '1px solid var(--border)',
                            fontSize: '1rem',
                            boxShadow: 'var(--shadow-sm)'
                        }}
                    />
                </div>
                <p style={{ alignSelf: 'center', color: 'var(--text-muted)', whiteSpace: 'nowrap' }}>
                    {filteredResponses.length} toplam cevap
                </p>
                <button
                    onClick={handleExportPDF}
                    style={{
                        backgroundColor: 'var(--surface)',
                        color: 'var(--foreground)',
                        border: '1px solid var(--border)',
                        padding: '10px 20px',
                        borderRadius: 'var(--radius)',
                        cursor: 'pointer',
                        fontWeight: 600
                    }}
                >
                    Tabloyu İndir (PDF)
                </button>
            </div>

            <div style={{ overflowX: 'auto', backgroundColor: 'var(--surface)', borderRadius: 'var(--radius-lg)', boxShadow: 'var(--shadow-sm)', border: '1px solid var(--border)' }}>
                <table style={{ width: '100%', borderCollapse: 'collapse' }}>
                    <thead>
                        <tr style={{ backgroundColor: 'var(--background)', borderBottom: '1px solid var(--border)' }}>
                            <th style={{ padding: '16px', textAlign: 'left', fontWeight: 600 }}>Müşteri</th>
                            <th style={{ padding: '16px', textAlign: 'left', fontWeight: 600 }}>Şirket</th>
                            <th style={{ padding: '16px', textAlign: 'center', fontWeight: 600 }}>Dil</th>
                            <th style={{ padding: '16px', textAlign: 'left', fontWeight: 600 }}>Tarih</th>
                            <th style={{ padding: '16px', width: '180px', textAlign: 'right' }}>İşlemler</th>
                        </tr>
                    </thead>
                    <tbody>
                        {filteredResponses.length === 0 ? (
                            <tr>
                                <td colSpan={5} style={{ padding: '40px', textAlign: 'center', color: 'var(--text-muted)' }}>
                                    {searchTerm ? 'Sonuç bulunamadı.' : 'Henüz cevap yok.'}
                                </td>
                            </tr>
                        ) : filteredResponses.map(response => {
                            let customer: any;
                            try {
                                customer = JSON.parse(response.customerInfo);
                            } catch {
                                customer = {};
                            }

                            return (
                                <tr
                                    key={response.id}
                                    style={{ borderBottom: '1px solid var(--border)', cursor: 'pointer', transition: 'background-color 0.2s' }}
                                    onClick={() => setSelectedResponse(response)}
                                    // Add hover effect via CSS classes generally, but here inline style for simple hover is hard. 
                                    // We rely on simple structure.
                                    onMouseEnter={(e) => e.currentTarget.style.backgroundColor = 'var(--background)'}
                                    onMouseLeave={(e) => e.currentTarget.style.backgroundColor = 'transparent'}
                                >
                                    <td style={{ padding: '16px', fontWeight: 600 }}>
                                        {customer.fullName}
                                    </td>
                                    <td style={{ padding: '16px', color: 'var(--text-muted)' }}>
                                        {customer.companyName}
                                    </td>
                                    <td style={{ padding: '16px', textAlign: 'center' }}>
                                        <span style={{
                                            padding: '4px 8px',
                                            borderRadius: '4px',
                                            backgroundColor: response.language === 'en' ? '#e3f2fd' : '#fff3e0',
                                            color: response.language === 'en' ? '#1565c0' : '#e65100',
                                            fontSize: '0.8rem',
                                            fontWeight: 600
                                        }}>
                                            {response.language === 'en' ? 'EN' : 'TR'}
                                        </span>
                                    </td>
                                    <td style={{ padding: '16px', color: 'var(--text-muted)' }}>
                                        {new Date(response.createdAt).toLocaleDateString(response.language === 'en' ? 'en-US' : 'tr-TR')}
                                    </td>
                                    <td style={{ padding: '16px', textAlign: 'right' }}>
                                        <button
                                            onClick={(e) => { e.stopPropagation(); handleSingleExport(response); }}
                                            style={{
                                                color: 'var(--primary)',
                                                background: 'none',
                                                border: 'none',
                                                cursor: 'pointer',
                                                fontWeight: 500,
                                                marginRight: '12px'
                                            }}
                                            title="PDF İndir"
                                        >
                                            PDF
                                        </button>
                                        <button
                                            onClick={(e) => { e.stopPropagation(); handleDelete(response.id); }}
                                            disabled={deleting === response.id}
                                            style={{
                                                color: 'var(--error)',
                                                background: 'none',
                                                border: 'none',
                                                cursor: 'pointer',
                                                fontWeight: 500,
                                                opacity: deleting === response.id ? 0.5 : 1
                                            }}
                                        >
                                            {deleting === response.id ? '...' : 'Sil'}
                                        </button>
                                    </td>
                                </tr>
                            );
                        })}
                    </tbody>
                </table>
            </div>
        </div>
    );
}
